
spring:
  application:
    name: gulimall-product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/mall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  redis:
    host: 192.168.56.10
  rabbitmq:
    host: 192.168.56.10
    virtual-host: /
    port: 5672
    publisher-confirm-type: correlated

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 10001
logging:
  level:
    com.example.gulimall: debug
